routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){
    Route::get('/', function() {
        return redirect()->route('public.beranda');
    });


    /**
     * Route for Public
     */
    Route::get('/public', function() {
        return redirect()->route('public.beranda');
    });

    Route::prefix('public')->name('public.')->group(function() {
        Route::get('/beranda', 'PublicController@beranda')->name('beranda');
        Route::get('/daftarUmkm', 'PublicController@daftarUmkm')->name('daftarUmkm');
        Route::get('/produkUmkm', 'PublicController@produkUmkm')->name('produkUmkm');
        Route::get('/produkUnggulan', 'PublicController@produkUnggulan')->name('produkUnggulan');
        Route::get('/jadwalPameran', 'PublicController@jadwalPameran')->name('jadwalPameran');
        Route::get('/bup', 'PublicController@bup')->name('bup');
        Route::get('/bup/create', 'PublicController@bupCreate')->name('bup.create');
        Route::post('/bup/store', 'PublicController@bupStore')->name('bup.store');
        Route::get('/bup/{pengumumanBup}/download', 'PublicController@bupDownload')->name('pengumumanBup.download');
    });

    Auth::routes();

    /**
     * Route for Admin
     */
    Route::get('/admin', function() {
        return redirect()->route('admin.beranda');
    });

    Route::prefix('admin')->name('admin.')->group(function() {
        Route::get('/beranda', 'AdminController@beranda')->name('beranda');

        // CRUD
        Route::resources([
            'pengguna' => PenggunaController::class,
            'daftarUmkm' => DaftarUmkmController::class,
            'produkUmkm' => ProdukUmkmController::class,
            'produkUnggulan' => ProdukUnggulanController::class,
            'jadwalPameran' => JadwalPameranController::class,
            'bup' => BupController::class,
            'pengumumanBup' => PengumumanBupController::class,
        ]);

        Route::get('/bup/{bup}/download/EKTP', 'BupController@downloadEKTP')->name('bup.download.ektp');
        Route::get('/bup/{bup}/download/KK_Pemilik', 'BupController@downloadKK_Pemilik')->name('bup.download.kk_pemilik');
        Route::get('/bup/{bup}/download/Buku_Tabungan', 'BupController@downloadBuku_Tabungan')->name('bup.download.buku_tabungan');
        Route::get('/bup/{bup}/download/Ket_Usaha', 'BupController@downloadKet_Usaha')->name('bup.download.ket_usaha');
        Route::get('/bup/{bup}/download/Pernyataan', 'BupController@downloadPernyataan')->name('bup.download.doc_pernyataan');

        Route::get('/pengumumanBup/{pengumumanBup}/download', 'PengumumanBupController@download')->name('pengumumanBup.download');
    });
});

app/Models/Bup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bup extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'bup';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id_bup';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];
}

app/Http/Controllers/BupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class BupController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->has('search'))
        {
            $bup = Bup::where('nib', 'like', '%'.$request->search.'%')
                            ->orWhere('nama_pemilik', 'like', '%'.$request->search.'%')
                            ->paginate(10)->withQueryString();
        }else{
            $bup = Bup::paginate(10);
        }
        return view('admin.bup.index', compact('bup'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->hak_akses == 'admin'){
            return view('admin.bup.create');
        }else{
            return redirect()->route('admin.bup.index')->with('warning', 'Anda tidak memiliki hak akses');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nib' => ['required', 'string', 'max:255', 'unique:bup'],
            'nama_pemilik' => ['required', 'string', 'max:255'],
            'nik' => ['required', 'string', 'min:16', 'max:255'],
            'no_rek' => ['required'],
            'ektp' => ['required'],
            'kk_pemilik' => ['required'],
            'ket_usaha' => ['required'],
            'buku_tabungan' => ['required'],
            'doc_pernyataan' => ['required'],
        ]);

        $ektp = $request->file('ektp')->storeAs(
            'pernyataan' , 'EKTP'.$request->nib, 'public'
        );

        $kk_pemilik = $request->file('kk_pemilik')->storeAs(
            'pernyataan' , 'KK'.$request->nib, 'public'
        );

        $ket_usaha = $request->file('ket_usaha')->storeAs(
            'pernyataan' , 'KU'.$request->nib, 'public'
        );

        $buku_tabungan = $request->file('buku_tabungan')->storeAs(
            'pernyataan' , 'BT'.$request->nib, 'public'
        );

        $doc_pernyataan = $request->file('doc_pernyataan')->storeAs(
            'pernyataan' , 'P'.$request->nib, 'public'
        );

        $store = $request->except(['ektp', 'kk_pemilik', 'ket_usaha', 'buku_tabungan', 'doc_pernyataan']);

        $store['ektp'] = $ektp;
        $store['kk_pemilik'] = $kk_pemilik;
        $store['ket_usaha'] = $ket_usaha;
        $store['buku_tabungan'] = $buku_tabungan;
        $store['doc_pernyataan'] = $doc_pernyataan;

        $bup = Bup::create($store);
        
        return redirect()->route('admin.bup.show', $bup)->with('success', 'Berhasil menambah BUP <strong>'.$bup->nib.'</strong>.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function show(Bup $bup)
    {
        return view('admin.bup.show', compact('bup'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function edit(Bup $bup)
    {
        if(Auth::user()->hak_akses == 'admin'){
            return view('admin.bup.edit', compact('bup'));
        }else{
            return redirect()->route('admin.bup.index')->with('warning', 'Anda tidak memiliki hak akses');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bup $bup)
    {
        $request->validate([
            'nib' => ['required', 'string', 'max:255', 'unique:bup,nib,'.$bup->id_bup.',id_bup'],
            'nama_pemilik' => ['required', 'string', 'max:255'],
            'nik' => ['required', 'string', 'min:16', 'max:255'],
            'no_rek' => ['required'],
        ]);
        
        $except = [];

        if($request->has('ektp')){
            Storage::disk('public')->delete($bup->ektp);
            $ektp = $request->file('ektp')->storeAs(
                'pernyataan' , 'EKTP'.$request->nib, 'public'
            );
            $except[] = 'ektp';
        }else{
            $ektp = false;
        }

        if($request->has('kk_pemilik')){
            Storage::disk('public')->delete($bup->kk_pemilik);
            $kk_pemilik = $request->file('kk_pemilik')->storeAs(
                'pernyataan' , 'KK'.$request->nib, 'public'
            );
            $except[] = 'kk_pemilik';
        }else{
            $kk_pemilik = false;
        }

        if($request->has('ket_usaha')){
            Storage::disk('public')->delete($bup->ket_usaha);
            $ket_usaha = $request->file('ket_usaha')->storeAs(
                'pernyataan' , 'KU'.$request->nib, 'public'
            );
            $except[] = 'ket_usaha';
        }else{
            $ket_usaha = false;
        }

        if($request->has('buku_tabungan')){
            Storage::disk('public')->delete($bup->buku_tabungan);
            $buku_tabungan = $request->file('buku_tabungan')->storeAs(
                'pernyataan' , 'BT'.$request->nib, 'public'
            );
            $except[] = 'buku_tabungan';
        }else{
            $buku_tabungan = false;
        }

        if($request->has('doc_pernyataan')){
            Storage::disk('public')->delete($bup->doc_pernyataan);
            $doc_pernyataan = $request->file('doc_pernyataan')->storeAs(
                'pernyataan' , 'P'.$request->nib, 'public'
            );
            $except[] = 'doc_pernyataan';
        }else{
            $doc_pernyataan = false;
        }

        if(count($except) > 0)
        {
            $update = $request->except($except);
            if($ektp){
                $update['ektp'] = $ektp;
            }
            if($kk_pemilik){
                $update['kk_pemilik'] = $kk_pemilik;
            }
            if($ket_usaha){
                $update['ket_usaha'] = $ket_usaha;
            }
            if($buku_tabungan){
                $update['buku_tabungan'] = $buku_tabungan;
            }
            if($doc_pernyataan){
                $update['doc_pernyataan'] = $doc_pernyataan;
            }
        }else{
            $update = $request->all();
        }

        $bup->update($update);
        
        return redirect()->route('admin.bup.show', $bup)->with('success', 'Berhasil mengubah BUP <strong>'.$bup->nib.'</strong>.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bup $bup)
    {
        if(Auth::user()->hak_akses == 'admin'){
            $name = $bup->nib;
            Storage::disk('public')->delete($bup->ektp);
            Storage::disk('public')->delete($bup->kk_pemilik);
            Storage::disk('public')->delete($bup->buku_tabungan);
            Storage::disk('public')->delete($bup->ket_usaha);
            Storage::disk('public')->delete($bup->doc_pernyataan);
            $bup->delete();
    
            return redirect()->route('admin.bup.index')->with('success', 'Berhasil menghapus BUP <strong>'.$name.'</strong>.');
        }else{
            return redirect()->route('admin.bup.index')->with('warning', 'Anda tidak memiliki hak akses');
        }
    }

    /**
     * Downloading Doc EKTP
     * 
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function downloadEKTP(Bup $bup)
    {
        $file= public_path(). Storage::url($bup->ektp);

        $headers = array(
                'Content-Type: application/pdf',
                );

        return response()->download($file, 'EKTP_'.$bup->nib.'.pdf', $headers);
    }

    /**
     * Downloading Doc KK_Pemilik
     * 
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function downloadKK_Pemilik(Bup $bup)
    {
        $file= public_path(). Storage::url($bup->kk_pemilik);

        $headers = array(
                'Content-Type: application/pdf',
                );

        return response()->download($file, 'KK_Pemilik_'.$bup->nib.'.pdf', $headers);
    }

    /**
     * Downloading Doc Buku_Tabungan
     * 
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function downloadBuku_Tabungan(Bup $bup)
    {
        $file= public_path(). Storage::url($bup->buku_tabungan);

        $headers = array(
                'Content-Type: application/pdf',
                );

        return response()->download($file, 'Buku_Tabungan_'.$bup->nib.'.pdf', $headers);
    }

    /**
     * Downloading Doc Ket_Usaha
     * 
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function downloadKet_Usaha(Bup $bup)
    {
        $file= public_path(). Storage::url($bup->ket_usaha);

        $headers = array(
                'Content-Type: application/pdf',
                );

        return response()->download($file, 'Ket_Usaha_'.$bup->nib.'.pdf', $headers);
    }

    /**
     * Downloading Doc Pernyataan
     * 
     * @param  \App\Models\Bup  $bup
     * @return \Illuminate\Http\Response
     */
    public function downloadPernyataan(Bup $bup)
    {
        $file= public_path(). Storage::url($bup->doc_pernyataan);

        $headers = array(

resources/views/admin/bup/view/form.blade.php
<form id="form-bup" action="{{ ($bup) ? route('admin.bup.update', $bup) : route('admin.bup.store') }}"id="form-bup" method="POST" enctype="multipart/form-data">
    @csrf
    <input type="hidden" name="_method" value="{{ ($bup) ? 'PUT' : 'POST' }}" />

    <div class="form-group row">
        <label for="nib" class="col-md-4 col-form-label text-md-right">{{ __('NIB') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <input id="nib" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('nib') is-invalid @enderror" name="nib" value="{{ (old('nib')) ? old('nib') : $bup->nib ?? '' }}" autocomplete="nib" required {{ ($form_open) ? 'autofocus' : 'readonly' }}>

            @error('nib')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="nama_pemilik" class="col-md-4 col-form-label text-md-right">{{ __('Nama Pemilik') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <input id="nama_pemilik" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('nama_pemilik') is-invalid @enderror" name="nama_pemilik" value="{{ (old('nama_pemilik')) ? old('nama_pemilik') : $bup->nama_pemilik ?? '' }}" autocomplete="nama_pemilik" required {{ ($form_open) ? '' : 'readonly' }}>

            @error('nama_pemilik')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group row">
        <label for="nik" class="col-md-4 col-form-label text-md-right">{{ __('NIK') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <input id="nik" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('nik') is-invalid @enderror" name="nik" value="{{ (old('nik')) ? old('nik') : $bup->nik ?? '' }}" autocomplete="nik" required {{ ($form_open) ? '' : 'readonly' }}>

            @error('nik')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="iumk" class="col-md-4 col-form-label text-md-right">{{ __('IUMK') }}</label>

        <div class="col-md-6">
            <input id="iumk" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('iumk') is-invalid @enderror" name="iumk" value="{{ (old('iumk')) ? old('iumk') : $bup->iumk ?? '' }}" autocomplete="iumk" {{ ($form_open) ? 'autofocus' : 'readonly' }}>

            @error('iumk')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="alamat_usaha" class="col-md-4 col-form-label text-md-right">{{ __('Alamat Usaha') }}</label>

        <div class="col-md-6">
            <textarea id="alamat_usaha" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('alamat_usaha') is-invalid @enderror" name="alamat_usaha" autocomplete="alamat_usaha" {{ ($form_open) ? '' : 'readonly' }}>{{ (old('alamat_usaha')) ? old('alamat_usaha') : $bup->alamat_usaha ?? '' }}</textarea>

            @error('alamat_usaha')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="telp_pemilik" class="col-md-4 col-form-label text-md-right">{{ __('Telepon Pemilik') }}</label>

        <div class="col-md-6">
            <input id="telp_pemilik" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('telp_pemilik') is-invalid @enderror" name="telp_pemilik" value="{{ (old('telp_pemilik')) ? old('telp_pemilik') : $bup->telp_pemilik ?? '' }}" autocomplete="telp_pemilik" {{ ($form_open) ? 'autofocus' : 'readonly' }}>

            @error('telp_pemilik')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="npwp" class="col-md-4 col-form-label text-md-right">{{ __('NPWP') }}</label>

        <div class="col-md-6">
            <input id="npwp" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('npwp') is-invalid @enderror" name="npwp" value="{{ (old('npwp')) ? old('npwp') : $bup->npwp ?? '' }}" autocomplete="npwp" {{ ($form_open) ? 'autofocus' : 'readonly' }}>

            @error('npwp')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="no_rek" class="col-md-4 col-form-label text-md-right">{{ __('No Rekening') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <input id="no_rek" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('no_rek') is-invalid @enderror" name="no_rek" value="{{ (old('no_rek')) ? old('no_rek') : $bup->no_rek ?? '' }}" autocomplete="no_rek" required {{ ($form_open) ? 'autofocus' : 'readonly' }}>

            @error('no_rek')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="ektp" class="col-md-4 col-form-label text-md-right">{{ __('EKTP') }}{!! ($bup) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

        <div class="col-md-6">
            @if ($form_open)
            <div class="custom-file">
                <input id="ektp" type="file" accept=".pdf" class="{{ ($form_open) ? 'custom-file-input' : 'form-control-plaintext' }} @error('ektp') is-invalid @enderror" name="ektp" value="{{ (old('ektp')) ? old('ektp') : $bup->ektp ?? '' }}" autocomplete="ektp" {{ ($bup) ? '' : 'required' }} {{ ($form_open) ? 'autofocus' : 'readonly' }}>
                <label class="custom-file-label" for="ektp">Choose file</label>
            </div>
            @endif
            @if ($bup)
            <div class="mt-2 col-12">
                <a href="{{ route('admin.bup.download.ektp', $bup) }}"><i class="fas fa-download"></i> &nbsp;SuratPernyataan_{{$bup->nib}}.pdf</a>
            </div>
            @endif
            @error('ektp')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="kk_pemilik" class="col-md-4 col-form-label text-md-right">{{ __('KK Pemilik') }}{!! ($bup) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

        <div class="col-md-6">
            @if ($form_open)
            <div class="custom-file">
                <input id="kk_pemilik" type="file" accept=".pdf" class="{{ ($form_open) ? 'custom-file-input' : 'form-control-plaintext' }} @error('kk_pemilik') is-invalid @enderror" name="kk_pemilik" value="{{ (old('kk_pemilik')) ? old('kk_pemilik') : $bup->kk_pemilik ?? '' }}" autocomplete="kk_pemilik" {{ ($bup) ? '' : 'required' }} {{ ($form_open) ? 'autofocus' : 'readonly' }}>
                <label class="custom-file-label" for="kk_pemilik">Choose file</label>
            </div>
            @endif
            @if ($bup)
            <div class="mt-2 col-12">
                <a href="{{ route('admin.bup.download.kk_pemilik', $bup) }}"><i class="fas fa-download"></i> &nbsp;SuratPernyataan_{{$bup->nib}}.pdf</a>
            </div>
            @endif
            @error('kk_pemilik')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="buku_tabungan" class="col-md-4 col-form-label text-md-right">{{ __('Buku Tabungan') }}{!! ($bup) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

        <div class="col-md-6">
            @if ($form_open)
            <div class="custom-file">
                <input id="buku_tabungan" type="file" accept=".pdf" class="{{ ($form_open) ? 'custom-file-input' : 'form-control-plaintext' }} @error('buku_tabungan') is-invalid @enderror" name="buku_tabungan" value="{{ (old('buku_tabungan')) ? old('buku_tabungan') : $bup->buku_tabungan ?? '' }}" autocomplete="buku_tabungan" {{ ($bup) ? '' : 'required' }} {{ ($form_open) ? 'autofocus' : 'readonly' }}>
                <label class="custom-file-label" for="buku_tabungan">Choose file</label>
            </div>
            @endif
            @if ($bup)
            <div class="mt-2 col-12">
                <a href="{{ route('admin.bup.download.buku_tabungan', $bup) }}"><i class="fas fa-download"></i> &nbsp;SuratPernyataan_{{$bup->nib}}.pdf</a>
            </div>
            @endif
            @error('buku_tabungan')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="ket_usaha" class="col-md-4 col-form-label text-md-right">{{ __('Ket. Usaha') }}{!! ($bup) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

        <div class="col-md-6">
            @if ($form_open)
            <div class="custom-file">
                <input id="ket_usaha" type="file" accept=".pdf" class="{{ ($form_open) ? 'custom-file-input' : 'form-control-plaintext' }} @error('ket_usaha') is-invalid @enderror" name="ket_usaha" value="{{ (old('ket_usaha')) ? old('ket_usaha') : $bup->ket_usaha ?? '' }}" autocomplete="ket_usaha" {{ ($bup) ? '' : 'required' }} {{ ($form_open) ? 'autofocus' : 'readonly' }}>
                <label class="custom-file-label" for="ket_usaha">Choose file</label>
            </div>
            @endif
            @if ($bup)
            <div class="mt-2 col-12">
                <a href="{{ route('admin.bup.download.ket_usaha', $bup) }}"><i class="fas fa-download"></i> &nbsp;SuratPernyataan_{{$bup->nib}}.pdf</a>
            </div>
            @endif
            @error('ket_usaha')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="doc_pernyataan" class="col-md-4 col-form-label text-md-right">{{ __('Dokumen Pernyataan') }}{!! ($bup) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

        <div class="col-md-6">
            @if ($form_open)
            <div class="custom-file">
                <input id="doc_pernyataan" type="file" accept=".pdf" class="{{ ($form_open) ? 'custom-file-input' : 'form-control-plaintext' }} @error('doc_pernyataan') is-invalid @enderror" name="doc_pernyataan" value="{{ (old('doc_pernyataan')) ? old('doc_pernyataan') : $bup->doc_pernyataan ?? '' }}" autocomplete="doc_pernyataan" {{ ($bup) ? '' : 'required' }} {{ ($form_open) ? 'autofocus' : 'readonly' }}>
                <label class="custom-file-label" for="doc_pernyataan">Choose file</label>
            </div>
            @endif
            @if ($bup)
            <div class="mt-2 col-12">
                <a href="{{ route('admin.bup.download.doc_pernyataan', $bup) }}"><i class="fas fa-download"></i> &nbsp;SuratPernyataan_{{$bup->nib}}.pdf</a>
            </div>
            @endif
            @error('doc_pernyataan')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    
    <button type="submit" style="display:none">SUBMIT</button>
</form>

resources/views/admin/bup/view/table.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>No</th>
                <th>NIB</th>
                <th>Nama Pemilik</th>
                <th>NIK</th>
                <th>IUMK</th>
                <th>Alamat Usaha</th>
                <th>Telp. Pemilik</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
        @if (count($data) <= 0)
            <tr>
                <td colspan="11" class="text-center text-muted">Belum ada Pengajuan BUP!</td>
            </tr>
        @endif
        @foreach ($data as $row)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td><a href="{{ route('admin.bup.show', $row) }}">{{ $row->nib }}</a></td>
                <td>{{ $row->nama_pemilik }}</td>
                <td>{{ $row->nik }}</td>
                <td>{{ $row->iumk }}</td>
                <td>{{ $row->alamat_usaha }}</td>
                <td>{{ $row->telp_pemilik }}</td>
                <td>
                    <form action="{{ route('admin.bup.destroy', $row) }}" id="form-delete" onsubmit="return confirm('Apakah anda yakin untuk menghapus {{ $row->nib }}?');" method="POST">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>    
@include('components.pagination', ['data' => $data])