routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){
    Route::get('/', function() {
        return redirect()->route('public.beranda');
    });


    /**
     * Route for Public
     */
    Route::get('/public', function() {
        return redirect()->route('public.beranda');
    });

    Route::prefix('public')->name('public.')->group(function() {
        Route::get('/beranda', 'PublicController@beranda')->name('beranda');
        Route::get('/daftarUmkm', 'PublicController@daftarUmkm')->name('daftarUmkm');
        Route::get('/produkUmkm', 'PublicController@produkUmkm')->name('produkUmkm');
        Route::get('/produkUnggulan', 'PublicController@produkUnggulan')->name('produkUnggulan');
        Route::get('/jadwalPameran', 'PublicController@jadwalPameran')->name('jadwalPameran');
        Route::get('/bup', 'PublicController@bup')->name('bup');
        Route::get('/bup/create', 'PublicController@bupCreate')->name('bup.create');
        Route::post('/bup/store', 'PublicController@bupStore')->name('bup.store');
        Route::get('/bup/{pengumumanBup}/download', 'PublicController@bupDownload')->name('pengumumanBup.download');
    });

    Auth::routes();

    /**
     * Route for Admin
     */
    Route::get('/admin', function() {
        return redirect()->route('admin.beranda');
    });

    Route::prefix('admin')->name('admin.')->group(function() {
        Route::get('/beranda', 'AdminController@beranda')->name('beranda');

        // CRUD
        Route::resources([
            'pengguna' => PenggunaController::class,
            'daftarUmkm' => DaftarUmkmController::class,
            'produkUmkm' => ProdukUmkmController::class,
            'produkUnggulan' => ProdukUnggulanController::class,
            'jadwalPameran' => JadwalPameranController::class,
            'bup' => BupController::class,
            'pengumumanBup' => PengumumanBupController::class,
        ]);

        Route::get('/bup/{bup}/download/EKTP', 'BupController@downloadEKTP')->name('bup.download.ektp');
        Route::get('/bup/{bup}/download/KK_Pemilik', 'BupController@downloadKK_Pemilik')->name('bup.download.kk_pemilik');
        Route::get('/bup/{bup}/download/Buku_Tabungan', 'BupController@downloadBuku_Tabungan')->name('bup.download.buku_tabungan');
        Route::get('/bup/{bup}/download/Ket_Usaha', 'BupController@downloadKet_Usaha')->name('bup.download.ket_usaha');
        Route::get('/bup/{bup}/download/Pernyataan', 'BupController@downloadPernyataan')->name('bup.download.doc_pernyataan');

        Route::get('/pengumumanBup/{pengumumanBup}/download', 'PengumumanBupController@download')->name('pengumumanBup.download');
    });
});

resources/views/admin/beranda.blade.php
@php
    $hak_akses = [
        'admin' => 'Admin',
        'staf_dpmpt' => 'Staf DPMPT',
        'staf_dkumkmp' => 'Staf DKUMKMP'
    ];
@endphp 
@extends('layouts.dashboard',[
    'title' => 'Beranda '.$hak_akses[Auth::user()->hak_akses],
    'page' => 'Beranda',
    'pageTitle' => 'Beranda',
])

@push('action-components')
    <h2>Beranda {{ $hak_akses[Auth::user()->hak_akses] }}</h2>
@endpush

@section('content')
    <div class="row">
        <div class="offset-md-1 col-md-10 offset-sm-1 col-sm-10 border border-secondary rounded text-center p-3">
            <h2>Selamat Datang di Halaman {{ $hak_akses[Auth::user()->hak_akses] }}!</h2>
            <a href="{{ route('admin.pengguna.edit', Auth::user()->id) }}" class="btn btn-primary text-white mt-2">Edit Profile</a>
            <div class="row mt-3">
                <div class="offset-sm-1 col-sm-10 offset-md-3 col-md-6 text-left">
                    <div class="row mt-1">
                        <div class="col-5">
                            NIK
                        </div>
                        <div class="col-1 text-center">
                            :
                        </div>
                        <div class="col-6">
                            {{ Auth::user()->nik_pengguna }}
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col-5">
                            Nama
                        </div>
                        <div class="col-1 text-center">
                            :
                        </div>
                        <div class="col-6">
                            {{ Auth::user()->nama_pengguna }}
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col-5">
                            Instansi
                        </div>
                        <div class="col-1 text-center">
                            :
                        </div>
                        <div class="col-6">
                            {{ Auth::user()->instansi }}
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col-5">
                            Nomor Telepon
                        </div>
                        <div class="col-1 text-center">
                            :
                        </div>
                        <div class="col-6">
                            {{ Auth::user()->no_telp }}
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col-5">
                            Alamat
                        </div>
                        <div class="col-1 text-center">
                            :
                        </div>
                        <div class="col-6">
                            {{ Auth::user()->alamat }}
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col-5">
                            Hak Akses
                        </div>
                        <div class="col-1 text-center">
                            :
                        </div>
                        <div class="col-6">
                            {{ $hak_akses[Auth::user()->hak_akses] }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection