routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'prevent-back-history'],function(){
    Route::get('/', function() {
        return redirect()->route('public.beranda');
    });


    /**
     * Route for Public
     */
    Route::get('/public', function() {
        return redirect()->route('public.beranda');
    });

    Route::prefix('public')->name('public.')->group(function() {
        Route::get('/beranda', 'PublicController@beranda')->name('beranda');
        Route::get('/daftarUmkm', 'PublicController@daftarUmkm')->name('daftarUmkm');
        Route::get('/produkUmkm', 'PublicController@produkUmkm')->name('produkUmkm');
        Route::get('/produkUnggulan', 'PublicController@produkUnggulan')->name('produkUnggulan');
        Route::get('/jadwalPameran', 'PublicController@jadwalPameran')->name('jadwalPameran');
        Route::get('/bup', 'PublicController@bup')->name('bup');
        Route::get('/bup/create', 'PublicController@bupCreate')->name('bup.create');
        Route::post('/bup/store', 'PublicController@bupStore')->name('bup.store');
        Route::get('/bup/{pengumumanBup}/download', 'PublicController@bupDownload')->name('pengumumanBup.download');
    });

    Auth::routes();

    /**
     * Route for Admin
     */
    Route::get('/admin', function() {
        return redirect()->route('admin.beranda');
    });

    Route::prefix('admin')->name('admin.')->group(function() {
        Route::get('/beranda', 'AdminController@beranda')->name('beranda');

        // CRUD
        Route::resources([
            'pengguna' => PenggunaController::class,
            'daftarUmkm' => DaftarUmkmController::class,
            'produkUmkm' => ProdukUmkmController::class,
            'produkUnggulan' => ProdukUnggulanController::class,
            'jadwalPameran' => JadwalPameranController::class,
            'bup' => BupController::class,
            'pengumumanBup' => PengumumanBupController::class,
        ]);

        Route::get('/bup/{bup}/download/EKTP', 'BupController@downloadEKTP')->name('bup.download.ektp');
        Route::get('/bup/{bup}/download/KK_Pemilik', 'BupController@downloadKK_Pemilik')->name('bup.download.kk_pemilik');
        Route::get('/bup/{bup}/download/Buku_Tabungan', 'BupController@downloadBuku_Tabungan')->name('bup.download.buku_tabungan');
        Route::get('/bup/{bup}/download/Ket_Usaha', 'BupController@downloadKet_Usaha')->name('bup.download.ket_usaha');
        Route::get('/bup/{bup}/download/Pernyataan', 'BupController@downloadPernyataan')->name('bup.download.doc_pernyataan');

        Route::get('/pengumumanBup/{pengumumanBup}/download', 'PengumumanBupController@download')->name('pengumumanBup.download');
    });
});

app/Http/Controllers/PenggunaController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class PenggunaController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->has('search'))
        {
            $pengguna = User::where('nik_pengguna', 'like', '%'.$request->search.'%')
                            ->orWhere('nama_pengguna', 'like', '%'.$request->search.'%')
                            ->paginate(10)->withQueryString();
        }else{
            $pengguna = User::paginate(10);
        }
        return view('admin.pengguna.index', compact('pengguna'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->hak_akses == 'admin'){
            return view('admin.pengguna.create');
        }else{
            return redirect()->route('admin.pengguna.index')->with('warning', 'Anda tidak memiliki hak akses');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nik_pengguna' => ['required', 'string', 'min:16', 'max:255', 'unique:pengguna'],
            'nama_pengguna' => ['required', 'string', 'max:255'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'instansi' => ['required', 'string'],
            'hak_akses' => ['required', 'string'],
        ]);
        $store = $request->except(['password_confirmation']);
        $store['password'] = Hash::make($request->password);

        $pengguna = User::create($store);
        
        return redirect()->route('admin.pengguna.show', $pengguna)->with('success', 'Berhasil menambah pengguna <strong>'.$pengguna->nik_pengguna.'</strong>.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function show(User $pengguna)
    {
        return view('admin.pengguna.show', compact('pengguna'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function edit(User $pengguna)
    {
        return view('admin.pengguna.edit', compact('pengguna'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $pengguna)
    {
        $validator = [
            'nik_pengguna' => ['required', 'string', 'min:16', 'max:255', 'unique:pengguna,nik_pengguna,'.$pengguna->id],
            'nama_pengguna' => ['required', 'string', 'max:255'],
            'instansi' => ['required', 'string'],
            'hak_akses' => ['required', 'string'],
        ];
        
        if($request->has('password') && $request->password != null){
            $validator['password'] = ['required', 'string', 'min:8', 'confirmed'];
            $update = $request->except(['password_confirmation']);
            $update['password'] = Hash::make($request->password);
        }else{
            $update = $request->except(['password', 'password_confirmation']);
        }
        $request->validate($validator);

        $pengguna->update($update);
        
        return redirect()->route('admin.pengguna.show', $pengguna)->with('success', 'Berhasil mengubah pengguna <strong>'.$pengguna->nik_pengguna.'</strong>.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $pengguna)
    {
        if(Auth::user()->hak_akses == 'admin'){
            $name = $pengguna->nik_pengguna;
            $pengguna->delete();
    
            return redirect()->route('admin.pengguna.index')->with('success', 'Berhasil menghapus pengguna <strong>'.$name.'</strong>.');
        }else{
            return redirect()->route('admin.pengguna.index')->with('warning', 'Anda tidak memiliki hak akses');
        }
    }
}

resources/views/admin/pengguna/view/form.blade.php
<form id="form-pengguna" action="{{ ($pengguna) ? route('admin.pengguna.update', $pengguna) : route('admin.pengguna.store') }}" method="POST">
    @csrf
    <input type="hidden" name="_method" value="{{ ($pengguna) ? 'PUT' : 'POST' }}" />

    <div class="form-group row">
        <label for="nik_pengguna" class="col-md-4 col-form-label text-md-right">{{ __('NIK Pengguna') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <input id="nik_pengguna" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('nik_pengguna') is-invalid @enderror" name="nik_pengguna" value="{{ (old('nik_pengguna')) ? old('nik_pengguna') : $pengguna->nik_pengguna ?? '' }}" autocomplete="nik_pengguna" required {{ ($form_open) ? 'autofocus' : 'readonly' }}>

            @error('nik_pengguna')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="nama_pengguna" class="col-md-4 col-form-label text-md-right">{{ __('Nama Pengguna') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <input id="nama_pengguna" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('nama_pengguna') is-invalid @enderror" name="nama_pengguna" value="{{ (old('nama_pengguna')) ? old('nama_pengguna') : $pengguna->nama_pengguna ?? '' }}" autocomplete="nama_pengguna" required {{ ($form_open) ? '' : 'readonly' }}>

            @error('nama_pengguna')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    @if($form_open)
        <div class="form-group row">
            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }} {!! ($pengguna) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

            <div class="col-md-6">
                <input id="password" type="password" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('password') is-invalid @enderror" name="password" value="" autocomplete="password" {{ ($pengguna) ? '' : 'required' }} {{ ($form_open) ? '' : 'readonly' }}>

                @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="password_confirmation" id="label_password_confirmation" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }} {!! ($pengguna) ? '' : '&nbsp;<span class="text-danger">*</span>' !!}</label>

            <div class="col-md-6">
                <input id="password_confirmation" type="password" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('password_confirmation') is-invalid @enderror" name="password_confirmation" value="{{ (old('password_confirmation')) ? old('password_confirmation') : $pengguna->password_confirmation ?? '' }}" autocomplete="password_confirmation" {{ ($pengguna) ? '' : 'required' }} {{ ($form_open) ? '' : 'readonly' }}>

                @error('password_confirmation')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
    @endif
    <div class="form-group row">
        <label for="instansi" class="col-md-4 col-form-label text-md-right">{{ __('Instansi') }} &nbsp;<span class="text-danger">*</span></label>

        <div class="col-md-6">
            <select id="instansi" class="form-control @error('instansi') is-invalid @enderror" name="instansi" required {{ ($form_open) ? '' : 'disabled' }}>
                <option value="" disabled selected>-- Instansi --</option>
                <option value="DKUMKMP" {{ (((old('instansi')) ? old('instansi') : $pengguna->instansi ?? '') == "DKUMKMP") ? 'selected' : '' }}>DKUMKMP</option>
                <option value="DPMPT" {{ (((old('instansi')) ? old('instansi') : $pengguna->instansi ?? '') == "DPMPT") ? 'selected' : '' }}>DPMPT</option>
            </select>

            @error('instansi')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="no_telp" class="col-md-4 col-form-label text-md-right">{{ __('Nomor Telepon') }}</label>

        <div class="col-md-6">
            <input id="no_telp" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('no_telp') is-invalid @enderror" name="no_telp" value="{{ (old('no_telp')) ? old('no_telp') : $pengguna->no_telp ?? '' }}" autocomplete="no_telp" {{ ($form_open) ? '' : 'readonly' }}>

            @error('no_telp')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="form-group row">
        <label for="alamat" class="col-md-4 col-form-label text-md-right">{{ __('Alamat') }}</label>

        <div class="col-md-6">
            <textarea id="alamat" type="text" class="{{ ($form_open) ? 'form-control' : 'form-control-plaintext' }} @error('alamat') is-invalid @enderror" name="alamat" autocomplete="alamat" {{ ($form_open) ? '' : 'readonly' }}>{{ (old('alamat')) ? old('alamat') : $pengguna->alamat ?? '' }}</textarea>

            @error('alamat')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    @if (Auth::user()->hak_akses == 'admin')
        <div class="form-group row">
            <label for="hak_akses" class="col-md-4 col-form-label text-md-right">{{ __('Hak Akses') }} &nbsp;<span class="text-danger">*</span></label>

            <div class="col-md-6">
                <select id="hak_akses" class="form-control @error('hak_akses') is-invalid @enderror" name="hak_akses" required {{ ($form_open) ? '' : 'disabled' }}>
                    <option id="hak_akses_disabled" value="" disabled selected>-- Hak Akses --</option>
                    <option id="hak_akses_staf_dpmpt" value="staf_dpmpt" {{ (((old('hak_akses')) ? old('hak_akses') : $pengguna->hak_akses ?? '') == "staf_dpmpt") ? 'selected' : '' }}>Staf DPMPT</option>
                    <option id="hak_akses_staf_dkumkmp" value="staf_dkumkmp" {{ (((old('hak_akses')) ? old('hak_akses') : $pengguna->hak_akses ?? '') == "staf_dkumkmp") ? 'selected' : '' }}>Staf DKUMKMP</option>
                    <option id="hak_akses_admin" value="admin" {{ (((old('hak_akses')) ? old('hak_akses') : $pengguna->hak_akses ?? '') == "admin") ? 'selected' : '' }}>Admin</option>
                </select>

                @error('hak_akses')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
    @endif
    <button type="submit" style="display:none">SUBMIT</button>
</form>

<script>
    $(document).ready(function() {
        $('#instansi').on('change keyup focus', function() {
            var value = $(this).val();
            console.log(value)
            if(value == 'DKUMKMP'){
                $('#hak_akses_disabled').show().prop('selected', true)
                $('#hak_akses_staf_dpmpt').hide()
                $('#hak_akses_staf_dkumkmp').show()
                $('#hak_akses_admin').show()
            }else if(value == 'DPMPT'){
                $('#hak_akses_staf_dpmpt').show().prop('selected', true)
                $('#hak_akses_staf_dkumkmp').hide()
                $('#hak_akses_admin').hide()
            }else{
                $('#hak_akses_disabled').show().prop('selected', true)
                $('#hak_akses_staf_dpmpt').hide()
                $('#hak_akses_staf_dkumkmp').hide()
                $('#hak_akses_admin').hide()
            }
        });
    });
</script>
@if ($pengguna && $form_open)
    <script>
        $(document).ready(function(){
            $('#password').on('change keyup focus', function() {
                var password = $(this).val();
                if(password.length > 0){
                    $('#password_confirmation').prop('required', true);
                    $('#label_password_confirmation').html('Confirm Password &nbsp;<span class="text-danger">*</span>');
                }else{
                    $('#password_confirmation').prop('required', false);
                    $('#label_password_confirmation').html('Confirm Password');
                }
            });

            
        });
    </script>
@endif

resources/views/admin/pengguna/view/table.blade.php
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>No</th>
                <th>NIK Pengguna</th>
                <th>Nama Pengguna</th>
                <th>Instansi</th>
                <th>No Telepon</th>
                <th>Alamat</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
        @if (count($data) <= 0)
            <tr>
                <td colspan="7" class="text-center text-muted">Belum ada Pengguna!</td>
            </tr>
        @endif
        @foreach ($data as $row)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td><a href="{{ route('admin.pengguna.show', $row) }}">{{ $row->nik_pengguna }}</a></td>
                <td>{{ $row->nama_pengguna }}</td>
                <td>{{ $row->instansi }}</td>
                <td>{{ $row->no_telp }}</td>
                <td>{{ $row->alamat }}</td>
                <td>
                    @if ($row->id != Auth::user()->id && Auth::user()->hak_akses == 'admin')
                        <form action="{{ route('admin.pengguna.destroy', $row) }}" id="form-delete" onsubmit="return confirm('Apakah anda yakin untuk menghapus {{ $row->nik_pengguna }}?');" method="POST">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                        </form>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>    
@include('components.pagination', ['data' => $data])